FROM resin/%%RESIN_MACHINE_NAME%%-python:3.6.1-wheezy

RUN apt-get update && apt-get install -y build-essential git

WORKDIR /root

RUN git clone https://github.com/adafruit/Adafruit_Python_DHT.git
WORKDIR /root/Adafruit_Python_DHT
RUN python setup.py install --force-pi2

WORKDIR /root/home-sensors

COPY . /root/home-sensors

RUN pip install -r requirements.txt

CMD ["python","loop.py"]
